Manejo del Login, usuario: 'abc' Pass: '123'
Decort/TodoListJs pull request #5
Opened 2022-07-07 00:47 UTC by Decort

2022-07-07 13:58 UTC, satico0518 commented on login.html
> +                <button class="login-button" type="button" onclick="capture()">Login</button>
este boton debe ser del tipo "submit"

2022-07-07 13:59 UTC, satico0518 commented on login.js
> +    }
esto esta mal formateado y debe revisar la logica de los if

2022-07-07 21:26 UTC, Decort commented on login.html
> +                <button class="login-button" type="button" onclick="capture()">Login</button>
ya se puso el boton como tipo submit

2022-07-07 21:26 UTC, Decort commented on login.js
> +    }
ya se revisó

2022-07-07 21:33 UTC, satico0518 commented on login.html
> +                <button class="login-button" type="submit" onclick="capture()">Login</button>
el evento onclick no debe ir aca

2022-07-07 21:35 UTC, satico0518 commented on login.js
> +    }
esta mal formateado el codigo

2022-07-07 21:35 UTC, satico0518 commented on login.js
> +    var password = document.getElementById('password').value;
en serio todavia usando "var" ????

2022-07-07 21:36 UTC, satico0518 commented on login.js
> +function capture(){
esta funcion no deberia ir, aca deberiamos es subscribirnos a un evento que genera el form cuando se le da cllick al boton

2022-07-07 21:37 UTC, satico0518 requested changes
como no hemos podido reunirnos ahi dejo los comentarios q iba a hacer en la call, por favor revisalos y corrigelos

2022-07-09 15:16 UTC, satico0518 commented on login.js
> +
Y estos espacios que?

2022-07-09 15:16 UTC, satico0518 commented on login.js
> +
Por qué esos espacios ?

2022-07-09 15:17 UTC, satico0518 approved these changes

2022-07-09 16:45 UTC, Decort commented on login.js
> +
todo va pegado sin espacios?

2022-07-11 14:38 UTC, Decort commented on login.js
> +    }
ya quedo bien formateado

2022-07-11 14:39 UTC, Decort commented on login.js
> +function capture(){
ya se cambió la funcion

2022-07-11 14:39 UTC, Decort commented on login.js
> +    var password = document.getElementById('password').value;
ya se cambió a let

2022-07-11 14:39 UTC, Decort commented on login.js
> +
ya se arreglo los espacios

2022-07-11 14:41 UTC, merged