Diseño de pantalla ToDoList finalizado
Decort/TodoListJs pull request #7
Opened 2022-07-12 20:02 UTC by Decort

2022-07-12 20:58 UTC, satico0518 commented on stylesToDoList.css
> +    margin: 20px 10px;
por que TODOS los elementos de la pagina deben tener este margin?

2022-07-12 20:59 UTC, satico0518 commented on stylesToDoList.css
> +    height: 6em;
esta altura se define con un atributo que ya trae el tag textarea

2022-07-12 21:00 UTC, satico0518 commented on stylesToDoList.css
> +.button-add:hover{
me gusta q estes usando pseudo elementos

2022-07-12 21:01 UTC, satico0518 commented on stylesToDoList.css
> +#tasks-list {
por que el estilo utilizando el id del componente?

2022-07-12 21:02 UTC, satico0518 commented on stylesToDoList.css
> +}
usualmente estos estilos como son globales van de primeros en el documento, podrian ir luego de los estilos del body

2022-07-12 21:03 UTC, satico0518 commented on stylesToDoList.css
> +}
y que pasa si yo mas adelante creo un nuevo h3 y no necesito estos estilos ??? no es muy intrusivo?

2022-07-12 21:04 UTC, satico0518 commented on toDoList.html
> +
y esta linea en blanco para q es?

2022-07-12 21:06 UTC, satico0518 commented on toDoList.html
> +                    <li class="list">Oh, and do not forget the bread<button class="edit-button">EDIT</button><button>DELETE</button></li>
yo le llamaria a esta clase mucho mejor "list-item". 
**list** como tal hace referencia al elemento **ul** no a los elementos hijos **li**

2022-07-12 21:12 UTC, satico0518 requested changes
ahi dejo unos comments

2022-07-12 22:38 UTC, Decort commented on stylesToDoList.css
> +}
se les asignó una clase a cada uno y se ordenaron en el css

2022-07-12 22:38 UTC, Decort commented on toDoList.html
> +
ya la quité :)

2022-07-12 22:38 UTC, Decort commented on toDoList.html
> +                    <li class="list">Oh, and do not forget the bread<button class="edit-button">EDIT</button><button>DELETE</button></li>
se cambió clase a "list-item"

2022-07-13 14:00 UTC, satico0518 approved these changes

2022-07-13 14:02 UTC, merged